
name = "hugo-apsho-space"
license = "MIT"
licenselink = "https://github.com/LarsDu/hugo-apsho-space/blob/master/LICENSE"
description = "Apsho Hugo Space – App Landing Page is for games."
homepage = "https://apsho-hugo.staticmania.com/"
tags = ['clean', 'minimal', 'agency', 'corporate', 'creative agency', 'creative studio', 'portfolio', 'staticmania', 'responsive', 'blog', 'customizable', 'company', 'creative', 'agency template']
features = ['bootstrap 4', 'responsive design', 'blog', 'responsive','landing-page', 'minimal', 'business', 'agency-template', 'hugo-theme', 'portfolio', 'company', 'creative', 'contact-form']
min_version = "0.41.0"

[author]
  name = "Static Mania and LarsDu"
  homepage = "https://du-blog.net/"