# MAIN base
baseURL = "https://apsho-hugo-space.netlify.app/"
languageCode = "en-us"
title = "Apsho Space | App landing template"
themesDir="../../"
theme = ["hugo-apsho-space"]

# Main button
[params.main_button]
link = "contact"
text = "Contact Us"

# Navigation Bar
[[menu.main]]
    name = "Home"
    url = "#hero"
    weight = 1
[[menu.main]]
    name = "About"
    url = "#feature"
    weight = 2
[[menu.main]]
    name = "PRESS"
    url = "#PRESS"
    weight = 3
[[menu.main]]
    name = "BLOG"
    url = "#blog"
    weight = 4
[[menu.main]]
    name = "FAQ"
    url = "#faq"
    weight = 3

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Latest Article"
    url = "/blog"
    weight = 2
[[menu.sitemap]]
    name = "Privacy & Policy"
    url = "/privacy"
    weight = 3
[[menu.sitemap]]
    name = "Contact"
    url = "/contact"
    weight = 4

# Footer Address
[params.address]
address = "23 Khan Niketon, Grand Street, NYK."
email = "apsho@example.com"
phone = "+(448) 833 5272 332"

# Footer Social
[params.social]
facebook = "https://www.facebook.com/pg/staticmania"
twitter = "https://twitter.com/static_mania"
github = "https://github.com/StaticMania"

[params]

# Mailchimp
mailchimp_form_action="#"
mailchimp_form_name="#"

# Header
logo = "images/logo.png"
formspreeURL = "https://formspree.io/mknyovwz"
googleAnalytics = ""

# Footer
footerTitle = "Get the latest app updates"
copyright1 = "All right reserved"
copyright2 = "Copyright © Apsho {year}"

#contact
email = "help@staticmania.com"